### ISSUE TITLE
.dll's missing.

### ISSUE THREAD

**Issue by ninjabou** [LRFLEW/OpenRCT2Launcher#13]
sorry if this is the wrong place to put this, but it seems im missing VCRUNTIME140.dll, and  MSVCP140.dll. do you know of any way to fix this? screenshots of errors: [http://i.imgur.com/7ybUe0g.png](http://i.imgur.com/28kzKTo.png) and [http://i.imgur.com/7ybUe0g.png](http://i.imgur.com/7ybUe0g.png)

**Comment by LRFLEW** [comment]
Did you download the .zip version? There is a file called `vcredist_x86.exe`. Run that, and it should fix the error. Let me know if you used the .exe installer I provided or if you just downloaded the .zip file, as well if that solution worked.

**Comment by rawr51919** [comment]
Since this is a Visual C++ runtime error, & not a real program bug, @LRFLEW should now close this issue.

**Comment by LRFLEW** [comment]
@coltongit Probably, but I'm going to leave it open for a little while longer because there's one case where this _is_ an actual issue. If the problem is that the installer I provide isn't automating this, then there is an issue. Once I can verify that the installer works as intended, I'll close it.

**Comment by ninjabou** [comment]
@LRFLEW thanks for answering, sorry i think i got the download process a bit messed up, and sorry i posted in the wrong place. it's working now.

**Comment by LRFLEW** [comment]
Sounds like this is a non-issue then. I'll go ahead and close it.
