### ISSUE TITLE
Refusing to use rct1 theme when setting is applied in launcher 

### ISSUE THREAD

**Issue by Ryder17z** [LRFLEW/OpenRCT2Launcher#17]
For whatever reason the setting was recently reset.

Applying this setting has no effect and the game is launched with rct2 theme.

Changing the setting inside openrct solves the issue

**Comment by LRFLEW** [comment]
That's weird. OpenRCT2 must have changed something upstream that broke this.

To be honest, this issue has already been fixed in the develop branch... in a way. I've heavily cut down the options menu in the launcher to avoid duplicating in-game settings when possible, which includes the setting you're describing. This issue will end up being solved indirectly when v0.0.6 comes out.

**Comment by Ryder17z** [comment]
Okay

**Comment by LRFLEW** [comment]
Closed, as the feature this issue is about was removed in v0.0.6
