### ISSUE TITLE
stable branch should be default

### ISSUE THREAD

**Issue by funkenstrahlen** [LRFLEW/OpenRCT2Launcher#2]

**Comment by LRFLEW** [comment]
I don't particularly want to change the default, both because it can affect people who used older versions of the launcher, and because I feel that people who want to stay on stable are less likely to use the launcher. The plan is to add a prompt for first-time users like the other launcher has. I'm willing to listen to feedback on this, though, so I'll leave this open to discussion.

**Comment by Gymnasiast** [comment]
A prompt would be better to allow users to make an informed choice. Most users do seem to prefer develop, so I disagree with the OP.

**Comment by rawr51919** [comment]
I think it should be a menu item in the options for the launcher whether it should be on stable or develop. The develop branch would be set by default.

**Comment by Broxzier** [comment]
It is already in the options window, right at the page when you open it.

**Comment by rawr51919** [comment]
Since there IS a menu item to figure out which branch you want to DL from, I'll let @LRFLEW close this one. develop is the default for MANY good reasons, such as bugfixes, etc.
