### ISSUE TITLE
Virus found in Launcher

### ISSUE THREAD

**Issue by sybenx** [LRFLEW/OpenRCT2Launcher#24]
https://www.virustotal.com/en/file/b12b9956e2e64982bdef9fbf8b1526ccacf146f14139d402cd8ca8c44ee0540b/analysis/

**Comment by Nubbie** [comment]
I extremely doubt it, the code is open source so you can check if there is
Just one anti virus scanner got triggered which I guess is a false positive
1/56 doesn't say that there is a virus :U

Edit: Seem like the anti virus also said its a "Heuristic" detection which means the anti virus ain't sure that it's a virus "but it acts suspicious" which can lead to false positives :)
Read more here https://en.m.wikipedia.org/wiki/Heuristic_analysis

**Comment by sybenx** [comment]
You're right. Did some extra research, lots of oversensitive antiviruses.
apologies for the false positive

**Comment by Nubbie** [comment]
No problem at all :)
It would be really worrying if all checks where marked :(

@lrflew seems to be solved :+1:

**Comment by LRFLEW** [comment]
To add to this, the "Heuristic" detection was likely due to the fact that the program launches another program that it downloads. That can be a very Trojan thing to do, so I can understand antivirus software's hesitance to consider this "safe". I've been having to deal with a similar issue with OpenMC2 (but with a lot more false positives). I can assure you, though, that there isn't any malware in the downloads (unless something's wrong with AppVeyor 😜), and if you are concerned, you can always build from source.

Closing this issue, as it's not really something that needs resolving.
